# Generated by Django 3.2.3 on 2021-06-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_reviews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogpost', verbose_name='Имя поста'),
        ),
    ]
