# Generated by Django 3.2.3 on 2021-05-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210524_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_type',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogtype', verbose_name='Тип поста'),
            preserve_default=False,
        ),
    ]
