# Generated by Django 3.2.3 on 2021-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_blogpost_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='salary',
            field=models.IntegerField(default=-1.0, max_length=255, verbose_name='Зарплата'),
            preserve_default=False,
        ),
    ]
