# Generated by Django 3.2.3 on 2021-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_blogpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.CharField(default=-1.0, max_length=255, verbose_name='Ссылка для связи'),
            preserve_default=False,
        ),
    ]
